require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AcademicHonorSocietiesController do

  # This should return the minimal set of attributes required to create a valid
  # AcademicHonorSociety. As you add validations to AcademicHonorSociety, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AcademicHonorSocietiesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all academic_honor_societies as @academic_honor_societies" do
      academic_honor_society = AcademicHonorSociety.create! valid_attributes
      get :index, {}, valid_session
      assigns(:academic_honor_societies).should eq([academic_honor_society])
    end
  end

  describe "GET show" do
    it "assigns the requested academic_honor_society as @academic_honor_society" do
      academic_honor_society = AcademicHonorSociety.create! valid_attributes
      get :show, {:id => academic_honor_society.to_param}, valid_session
      assigns(:academic_honor_society).should eq(academic_honor_society)
    end
  end

  describe "GET new" do
    it "assigns a new academic_honor_society as @academic_honor_society" do
      get :new, {}, valid_session
      assigns(:academic_honor_society).should be_a_new(AcademicHonorSociety)
    end
  end

  describe "GET edit" do
    it "assigns the requested academic_honor_society as @academic_honor_society" do
      academic_honor_society = AcademicHonorSociety.create! valid_attributes
      get :edit, {:id => academic_honor_society.to_param}, valid_session
      assigns(:academic_honor_society).should eq(academic_honor_society)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AcademicHonorSociety" do
        expect {
          post :create, {:academic_honor_society => valid_attributes}, valid_session
        }.to change(AcademicHonorSociety, :count).by(1)
      end

      it "assigns a newly created academic_honor_society as @academic_honor_society" do
        post :create, {:academic_honor_society => valid_attributes}, valid_session
        assigns(:academic_honor_society).should be_a(AcademicHonorSociety)
        assigns(:academic_honor_society).should be_persisted
      end

      it "redirects to the created academic_honor_society" do
        post :create, {:academic_honor_society => valid_attributes}, valid_session
        response.should redirect_to(AcademicHonorSociety.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved academic_honor_society as @academic_honor_society" do
        # Trigger the behavior that occurs when invalid params are submitted
        AcademicHonorSociety.any_instance.stub(:save).and_return(false)
        post :create, {:academic_honor_society => { "name" => "invalid value" }}, valid_session
        assigns(:academic_honor_society).should be_a_new(AcademicHonorSociety)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AcademicHonorSociety.any_instance.stub(:save).and_return(false)
        post :create, {:academic_honor_society => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested academic_honor_society" do
        academic_honor_society = AcademicHonorSociety.create! valid_attributes
        # Assuming there are no other academic_honor_societies in the database, this
        # specifies that the AcademicHonorSociety created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AcademicHonorSociety.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => academic_honor_society.to_param, :academic_honor_society => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested academic_honor_society as @academic_honor_society" do
        academic_honor_society = AcademicHonorSociety.create! valid_attributes
        put :update, {:id => academic_honor_society.to_param, :academic_honor_society => valid_attributes}, valid_session
        assigns(:academic_honor_society).should eq(academic_honor_society)
      end

      it "redirects to the academic_honor_society" do
        academic_honor_society = AcademicHonorSociety.create! valid_attributes
        put :update, {:id => academic_honor_society.to_param, :academic_honor_society => valid_attributes}, valid_session
        response.should redirect_to(academic_honor_society)
      end
    end

    describe "with invalid params" do
      it "assigns the academic_honor_society as @academic_honor_society" do
        academic_honor_society = AcademicHonorSociety.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AcademicHonorSociety.any_instance.stub(:save).and_return(false)
        put :update, {:id => academic_honor_society.to_param, :academic_honor_society => { "name" => "invalid value" }}, valid_session
        assigns(:academic_honor_society).should eq(academic_honor_society)
      end

      it "re-renders the 'edit' template" do
        academic_honor_society = AcademicHonorSociety.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AcademicHonorSociety.any_instance.stub(:save).and_return(false)
        put :update, {:id => academic_honor_society.to_param, :academic_honor_society => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested academic_honor_society" do
      academic_honor_society = AcademicHonorSociety.create! valid_attributes
      expect {
        delete :destroy, {:id => academic_honor_society.to_param}, valid_session
      }.to change(AcademicHonorSociety, :count).by(-1)
    end

    it "redirects to the academic_honor_societies list" do
      academic_honor_society = AcademicHonorSociety.create! valid_attributes
      delete :destroy, {:id => academic_honor_society.to_param}, valid_session
      response.should redirect_to(academic_honor_societies_url)
    end
  end

end
