require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GraduateAssistantshipsController do

  # This should return the minimal set of attributes required to create a valid
  # GraduateAssistantship. As you add validations to GraduateAssistantship, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "division" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GraduateAssistantshipsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all graduate_assistantships as @graduate_assistantships" do
      graduate_assistantship = GraduateAssistantship.create! valid_attributes
      get :index, {}, valid_session
      assigns(:graduate_assistantships).should eq([graduate_assistantship])
    end
  end

  describe "GET show" do
    it "assigns the requested graduate_assistantship as @graduate_assistantship" do
      graduate_assistantship = GraduateAssistantship.create! valid_attributes
      get :show, {:id => graduate_assistantship.to_param}, valid_session
      assigns(:graduate_assistantship).should eq(graduate_assistantship)
    end
  end

  describe "GET new" do
    it "assigns a new graduate_assistantship as @graduate_assistantship" do
      get :new, {}, valid_session
      assigns(:graduate_assistantship).should be_a_new(GraduateAssistantship)
    end
  end

  describe "GET edit" do
    it "assigns the requested graduate_assistantship as @graduate_assistantship" do
      graduate_assistantship = GraduateAssistantship.create! valid_attributes
      get :edit, {:id => graduate_assistantship.to_param}, valid_session
      assigns(:graduate_assistantship).should eq(graduate_assistantship)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GraduateAssistantship" do
        expect {
          post :create, {:graduate_assistantship => valid_attributes}, valid_session
        }.to change(GraduateAssistantship, :count).by(1)
      end

      it "assigns a newly created graduate_assistantship as @graduate_assistantship" do
        post :create, {:graduate_assistantship => valid_attributes}, valid_session
        assigns(:graduate_assistantship).should be_a(GraduateAssistantship)
        assigns(:graduate_assistantship).should be_persisted
      end

      it "redirects to the created graduate_assistantship" do
        post :create, {:graduate_assistantship => valid_attributes}, valid_session
        response.should redirect_to(GraduateAssistantship.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved graduate_assistantship as @graduate_assistantship" do
        # Trigger the behavior that occurs when invalid params are submitted
        GraduateAssistantship.any_instance.stub(:save).and_return(false)
        post :create, {:graduate_assistantship => { "division" => "invalid value" }}, valid_session
        assigns(:graduate_assistantship).should be_a_new(GraduateAssistantship)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        GraduateAssistantship.any_instance.stub(:save).and_return(false)
        post :create, {:graduate_assistantship => { "division" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested graduate_assistantship" do
        graduate_assistantship = GraduateAssistantship.create! valid_attributes
        # Assuming there are no other graduate_assistantships in the database, this
        # specifies that the GraduateAssistantship created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        GraduateAssistantship.any_instance.should_receive(:update_attributes).with({ "division" => "MyString" })
        put :update, {:id => graduate_assistantship.to_param, :graduate_assistantship => { "division" => "MyString" }}, valid_session
      end

      it "assigns the requested graduate_assistantship as @graduate_assistantship" do
        graduate_assistantship = GraduateAssistantship.create! valid_attributes
        put :update, {:id => graduate_assistantship.to_param, :graduate_assistantship => valid_attributes}, valid_session
        assigns(:graduate_assistantship).should eq(graduate_assistantship)
      end

      it "redirects to the graduate_assistantship" do
        graduate_assistantship = GraduateAssistantship.create! valid_attributes
        put :update, {:id => graduate_assistantship.to_param, :graduate_assistantship => valid_attributes}, valid_session
        response.should redirect_to(graduate_assistantship)
      end
    end

    describe "with invalid params" do
      it "assigns the graduate_assistantship as @graduate_assistantship" do
        graduate_assistantship = GraduateAssistantship.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GraduateAssistantship.any_instance.stub(:save).and_return(false)
        put :update, {:id => graduate_assistantship.to_param, :graduate_assistantship => { "division" => "invalid value" }}, valid_session
        assigns(:graduate_assistantship).should eq(graduate_assistantship)
      end

      it "re-renders the 'edit' template" do
        graduate_assistantship = GraduateAssistantship.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GraduateAssistantship.any_instance.stub(:save).and_return(false)
        put :update, {:id => graduate_assistantship.to_param, :graduate_assistantship => { "division" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested graduate_assistantship" do
      graduate_assistantship = GraduateAssistantship.create! valid_attributes
      expect {
        delete :destroy, {:id => graduate_assistantship.to_param}, valid_session
      }.to change(GraduateAssistantship, :count).by(-1)
    end

    it "redirects to the graduate_assistantships list" do
      graduate_assistantship = GraduateAssistantship.create! valid_attributes
      delete :destroy, {:id => graduate_assistantship.to_param}, valid_session
      response.should redirect_to(graduate_assistantships_url)
    end
  end

end
