require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OthersController do

  # This should return the minimal set of attributes required to create a valid
  # Other. As you add validations to Other, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "organization" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OthersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all others as @others" do
      other = Other.create! valid_attributes
      get :index, {}, valid_session
      assigns(:others).should eq([other])
    end
  end

  describe "GET show" do
    it "assigns the requested other as @other" do
      other = Other.create! valid_attributes
      get :show, {:id => other.to_param}, valid_session
      assigns(:other).should eq(other)
    end
  end

  describe "GET new" do
    it "assigns a new other as @other" do
      get :new, {}, valid_session
      assigns(:other).should be_a_new(Other)
    end
  end

  describe "GET edit" do
    it "assigns the requested other as @other" do
      other = Other.create! valid_attributes
      get :edit, {:id => other.to_param}, valid_session
      assigns(:other).should eq(other)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Other" do
        expect {
          post :create, {:other => valid_attributes}, valid_session
        }.to change(Other, :count).by(1)
      end

      it "assigns a newly created other as @other" do
        post :create, {:other => valid_attributes}, valid_session
        assigns(:other).should be_a(Other)
        assigns(:other).should be_persisted
      end

      it "redirects to the created other" do
        post :create, {:other => valid_attributes}, valid_session
        response.should redirect_to(Other.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved other as @other" do
        # Trigger the behavior that occurs when invalid params are submitted
        Other.any_instance.stub(:save).and_return(false)
        post :create, {:other => { "organization" => "invalid value" }}, valid_session
        assigns(:other).should be_a_new(Other)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Other.any_instance.stub(:save).and_return(false)
        post :create, {:other => { "organization" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested other" do
        other = Other.create! valid_attributes
        # Assuming there are no other others in the database, this
        # specifies that the Other created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Other.any_instance.should_receive(:update_attributes).with({ "organization" => "MyString" })
        put :update, {:id => other.to_param, :other => { "organization" => "MyString" }}, valid_session
      end

      it "assigns the requested other as @other" do
        other = Other.create! valid_attributes
        put :update, {:id => other.to_param, :other => valid_attributes}, valid_session
        assigns(:other).should eq(other)
      end

      it "redirects to the other" do
        other = Other.create! valid_attributes
        put :update, {:id => other.to_param, :other => valid_attributes}, valid_session
        response.should redirect_to(other)
      end
    end

    describe "with invalid params" do
      it "assigns the other as @other" do
        other = Other.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Other.any_instance.stub(:save).and_return(false)
        put :update, {:id => other.to_param, :other => { "organization" => "invalid value" }}, valid_session
        assigns(:other).should eq(other)
      end

      it "re-renders the 'edit' template" do
        other = Other.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Other.any_instance.stub(:save).and_return(false)
        put :update, {:id => other.to_param, :other => { "organization" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested other" do
      other = Other.create! valid_attributes
      expect {
        delete :destroy, {:id => other.to_param}, valid_session
      }.to change(Other, :count).by(-1)
    end

    it "redirects to the others list" do
      other = Other.create! valid_attributes
      delete :destroy, {:id => other.to_param}, valid_session
      response.should redirect_to(others_url)
    end
  end

end
