require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ScholarshipgrantsController do

  # This should return the minimal set of attributes required to create a valid
  # Scholarshipgrant. As you add validations to Scholarshipgrant, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "organization" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ScholarshipgrantsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all scholarshipgrants as @scholarshipgrants" do
      scholarshipgrant = Scholarshipgrant.create! valid_attributes
      get :index, {}, valid_session
      assigns(:scholarshipgrants).should eq([scholarshipgrant])
    end
  end

  describe "GET show" do
    it "assigns the requested scholarshipgrant as @scholarshipgrant" do
      scholarshipgrant = Scholarshipgrant.create! valid_attributes
      get :show, {:id => scholarshipgrant.to_param}, valid_session
      assigns(:scholarshipgrant).should eq(scholarshipgrant)
    end
  end

  describe "GET new" do
    it "assigns a new scholarshipgrant as @scholarshipgrant" do
      get :new, {}, valid_session
      assigns(:scholarshipgrant).should be_a_new(Scholarshipgrant)
    end
  end

  describe "GET edit" do
    it "assigns the requested scholarshipgrant as @scholarshipgrant" do
      scholarshipgrant = Scholarshipgrant.create! valid_attributes
      get :edit, {:id => scholarshipgrant.to_param}, valid_session
      assigns(:scholarshipgrant).should eq(scholarshipgrant)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Scholarshipgrant" do
        expect {
          post :create, {:scholarshipgrant => valid_attributes}, valid_session
        }.to change(Scholarshipgrant, :count).by(1)
      end

      it "assigns a newly created scholarshipgrant as @scholarshipgrant" do
        post :create, {:scholarshipgrant => valid_attributes}, valid_session
        assigns(:scholarshipgrant).should be_a(Scholarshipgrant)
        assigns(:scholarshipgrant).should be_persisted
      end

      it "redirects to the created scholarshipgrant" do
        post :create, {:scholarshipgrant => valid_attributes}, valid_session
        response.should redirect_to(Scholarshipgrant.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved scholarshipgrant as @scholarshipgrant" do
        # Trigger the behavior that occurs when invalid params are submitted
        Scholarshipgrant.any_instance.stub(:save).and_return(false)
        post :create, {:scholarshipgrant => { "organization" => "invalid value" }}, valid_session
        assigns(:scholarshipgrant).should be_a_new(Scholarshipgrant)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Scholarshipgrant.any_instance.stub(:save).and_return(false)
        post :create, {:scholarshipgrant => { "organization" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested scholarshipgrant" do
        scholarshipgrant = Scholarshipgrant.create! valid_attributes
        # Assuming there are no other scholarshipgrants in the database, this
        # specifies that the Scholarshipgrant created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Scholarshipgrant.any_instance.should_receive(:update_attributes).with({ "organization" => "MyString" })
        put :update, {:id => scholarshipgrant.to_param, :scholarshipgrant => { "organization" => "MyString" }}, valid_session
      end

      it "assigns the requested scholarshipgrant as @scholarshipgrant" do
        scholarshipgrant = Scholarshipgrant.create! valid_attributes
        put :update, {:id => scholarshipgrant.to_param, :scholarshipgrant => valid_attributes}, valid_session
        assigns(:scholarshipgrant).should eq(scholarshipgrant)
      end

      it "redirects to the scholarshipgrant" do
        scholarshipgrant = Scholarshipgrant.create! valid_attributes
        put :update, {:id => scholarshipgrant.to_param, :scholarshipgrant => valid_attributes}, valid_session
        response.should redirect_to(scholarshipgrant)
      end
    end

    describe "with invalid params" do
      it "assigns the scholarshipgrant as @scholarshipgrant" do
        scholarshipgrant = Scholarshipgrant.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Scholarshipgrant.any_instance.stub(:save).and_return(false)
        put :update, {:id => scholarshipgrant.to_param, :scholarshipgrant => { "organization" => "invalid value" }}, valid_session
        assigns(:scholarshipgrant).should eq(scholarshipgrant)
      end

      it "re-renders the 'edit' template" do
        scholarshipgrant = Scholarshipgrant.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Scholarshipgrant.any_instance.stub(:save).and_return(false)
        put :update, {:id => scholarshipgrant.to_param, :scholarshipgrant => { "organization" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested scholarshipgrant" do
      scholarshipgrant = Scholarshipgrant.create! valid_attributes
      expect {
        delete :destroy, {:id => scholarshipgrant.to_param}, valid_session
      }.to change(Scholarshipgrant, :count).by(-1)
    end

    it "redirects to the scholarshipgrants list" do
      scholarshipgrant = Scholarshipgrant.create! valid_attributes
      delete :destroy, {:id => scholarshipgrant.to_param}, valid_session
      response.should redirect_to(scholarshipgrants_url)
    end
  end

end
