require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UniversityHonorSocietiesController do

  # This should return the minimal set of attributes required to create a valid
  # UniversityHonorSociety. As you add validations to UniversityHonorSociety, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "organization" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UniversityHonorSocietiesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all university_honor_societies as @university_honor_societies" do
      university_honor_society = UniversityHonorSociety.create! valid_attributes
      get :index, {}, valid_session
      assigns(:university_honor_societies).should eq([university_honor_society])
    end
  end

  describe "GET show" do
    it "assigns the requested university_honor_society as @university_honor_society" do
      university_honor_society = UniversityHonorSociety.create! valid_attributes
      get :show, {:id => university_honor_society.to_param}, valid_session
      assigns(:university_honor_society).should eq(university_honor_society)
    end
  end

  describe "GET new" do
    it "assigns a new university_honor_society as @university_honor_society" do
      get :new, {}, valid_session
      assigns(:university_honor_society).should be_a_new(UniversityHonorSociety)
    end
  end

  describe "GET edit" do
    it "assigns the requested university_honor_society as @university_honor_society" do
      university_honor_society = UniversityHonorSociety.create! valid_attributes
      get :edit, {:id => university_honor_society.to_param}, valid_session
      assigns(:university_honor_society).should eq(university_honor_society)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new UniversityHonorSociety" do
        expect {
          post :create, {:university_honor_society => valid_attributes}, valid_session
        }.to change(UniversityHonorSociety, :count).by(1)
      end

      it "assigns a newly created university_honor_society as @university_honor_society" do
        post :create, {:university_honor_society => valid_attributes}, valid_session
        assigns(:university_honor_society).should be_a(UniversityHonorSociety)
        assigns(:university_honor_society).should be_persisted
      end

      it "redirects to the created university_honor_society" do
        post :create, {:university_honor_society => valid_attributes}, valid_session
        response.should redirect_to(UniversityHonorSociety.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved university_honor_society as @university_honor_society" do
        # Trigger the behavior that occurs when invalid params are submitted
        UniversityHonorSociety.any_instance.stub(:save).and_return(false)
        post :create, {:university_honor_society => { "organization" => "invalid value" }}, valid_session
        assigns(:university_honor_society).should be_a_new(UniversityHonorSociety)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        UniversityHonorSociety.any_instance.stub(:save).and_return(false)
        post :create, {:university_honor_society => { "organization" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested university_honor_society" do
        university_honor_society = UniversityHonorSociety.create! valid_attributes
        # Assuming there are no other university_honor_societies in the database, this
        # specifies that the UniversityHonorSociety created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        UniversityHonorSociety.any_instance.should_receive(:update_attributes).with({ "organization" => "MyString" })
        put :update, {:id => university_honor_society.to_param, :university_honor_society => { "organization" => "MyString" }}, valid_session
      end

      it "assigns the requested university_honor_society as @university_honor_society" do
        university_honor_society = UniversityHonorSociety.create! valid_attributes
        put :update, {:id => university_honor_society.to_param, :university_honor_society => valid_attributes}, valid_session
        assigns(:university_honor_society).should eq(university_honor_society)
      end

      it "redirects to the university_honor_society" do
        university_honor_society = UniversityHonorSociety.create! valid_attributes
        put :update, {:id => university_honor_society.to_param, :university_honor_society => valid_attributes}, valid_session
        response.should redirect_to(university_honor_society)
      end
    end

    describe "with invalid params" do
      it "assigns the university_honor_society as @university_honor_society" do
        university_honor_society = UniversityHonorSociety.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UniversityHonorSociety.any_instance.stub(:save).and_return(false)
        put :update, {:id => university_honor_society.to_param, :university_honor_society => { "organization" => "invalid value" }}, valid_session
        assigns(:university_honor_society).should eq(university_honor_society)
      end

      it "re-renders the 'edit' template" do
        university_honor_society = UniversityHonorSociety.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UniversityHonorSociety.any_instance.stub(:save).and_return(false)
        put :update, {:id => university_honor_society.to_param, :university_honor_society => { "organization" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested university_honor_society" do
      university_honor_society = UniversityHonorSociety.create! valid_attributes
      expect {
        delete :destroy, {:id => university_honor_society.to_param}, valid_session
      }.to change(UniversityHonorSociety, :count).by(-1)
    end

    it "redirects to the university_honor_societies list" do
      university_honor_society = UniversityHonorSociety.create! valid_attributes
      delete :destroy, {:id => university_honor_society.to_param}, valid_session
      response.should redirect_to(university_honor_societies_url)
    end
  end

end
